title: "Besturingssystemen"
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme
  - jemoji

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Aux links for the upper right navigation
aux_links:
  "Toledo":
    - "//p.cygnus.cc.kuleuven.be/webapps/blackboard/execute/announcement?method=search&context=course&course_id=_1012677_1&handle=cp_announcements&mode=cpview"
  "Classroom":
    - "//classroom.github.com/classrooms/91612922-besturingssystemen-2021-2022"
  "Forum":
    - "//github.com/besturingssystemen/xv6-riscv/discussions"
  "xv6 boek":
    - "//github.com/besturingssystemen/xv6-riscv-book/releases/latest/download/book.pdf"
  "Syllabus":
    - "//onderwijsaanbod.kuleuven.be/syllabi/n/G0Q35AN.htm"
  "Uurrooster":
    - "//webwsp.aps.kuleuven.be/sap(bD1ubCZjPTIwMA==)/public/bsp/sap/z_mijnuurrstrs/uurrooster.htm?sap-params=YmVndXVyX2ZpcnN0PTEwJTNhMzAlM2EwMCZlbmR1dXJfbGFzdD0xNiUzYTAwJTNhMDAmb3R5cGU9U00mb2JqaWQ9NTAzMDcwNzQmc2Nfb2JqaWQ9MDAwMDAwMDAmc2Vzc2lvbmlkPTAwNTA1Njk0QzhDMzFFRUM4QTgyNzgyMUNCQkQzNjZGJnR5cGVfZ3JvZXA9"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

collections:
  course:
    permalink: "/:collection/:path/"
    output: true
  oefeningen:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    course:
      name: Besturingssysteemen
    oefeningen:
      name: Oefenzittingen
    tutorials:
      name: Tutorials
